### ISSUE TITLE
TypeError: Network request failed when using in jest tests from React app

### ISSUE THREAD

**Issue by marcinczenko** [developit/jsdom-worker#5]
PROBLEM: inline workers do not seem to work in a jest-test. When running tests the following error occurs:

```bash
console.error node_modules/jsdom-worker/dist/jsdom-inline-worker.js:1
    TypeError: Network request failed
```

Steps to reproduce:

1. Create a React app with create-react-app
2. Add `jsdom-worker` and `node-fetch`, which is a peer dependency for `jsdom-worker`
3. Add the following test to the `App.test.js`:

    ```javascript
    it('works', async () => {
      let code = `onmessage = e => postMessage(e.data*2)`
      const blob = new Blob([code], {type: "application/javascript"})
      let worker = new Worker(URL.createObjectURL(blob))
      worker.onmessage = jest.fn()
      worker.postMessage(5) // 10
      expect(worker.onmessage).toHaveBeenCalledWith({ data: 10 })
   })
    ```
    and add `import 'jsdom-worker'` on top

Run the tests and you will see the error.

**Comment by marcinczenko** [comment]
It seems that when running jest test in watch mode, after executing tests `global.fetch` can be restored to the original, even though `global.URL` is **not** reset to `undefined`. In such a case `global.fetch` is not replaced with "jsdom-worker"-aware version when `jsdom-worker` code is executed on the next run and therefore one may get the `Network request failed` error.

My workaround is to check for an attribute on the `fetch` and `URL.createObjectURL` functions that I set when creating a replacements:

```javascript
if (!global.URL) global.URL = {};
if (!global.URL.$$objects) {
  global.URL.$$objects = new Map();
  global.URL.createObjectURL = blob => {
    let id = uuid();
    global.URL.$$objects[id] = blob;
    return `blob:http://localhost/${id}`;
  };
  global.URL.createObjectURL.jsdomWorker = true
}

if (global.URL.createObjectURL.jsdomWorker && !global.fetch.jsdomWorker) {
  let oldFetch = global.fetch || fetch;
  global.fetch = function(url, opts) {
    if (url.match(/^blob:/)) {
      return new Promise( (resolve, reject) => {
        let fr = new FileReader();
        fr.onload = () => {
            let Res = global.Response || Response;
            resolve(new Res(fr.result, { status: 200, statusText: 'OK' }));
        };
        fr.onerror = () => {
          reject(fr.error);
        };
        let id = url.match(/[^/]+$/)[0];
        fr.readAsText(global.URL.$$objects[id]);
      });
    }
    return oldFetch.call(this, url, opts);
  };
  global.fetch.jsdomWorker = true
}

// the rest without changes
// ...
```

Also, when testing one should pay attention to asynchronous code:

```javascript
it('works', done => {
  let code = `onmessage = e => postMessage(e.data*2)`
  const blob = new Blob([code], {type: "application/javascript"})
  let worker = new Worker(URL.createObjectURL(blob))
  worker.onmessage = data => {
    expect(data).toEqual({ data: 10 })
    done()
  }
  worker.postMessage(5) // 10
})
```

Perhaps you know some better way of solving it. If you think this is sufficient I may also create a pull request and update documentation accordingly.

**Comment by marcinczenko** [comment]
There is one more thing. When using workers it seems to be a good practice to use `self.onmessage` in the worker file (see 
https://github.com/facebook/create-react-app/issues/1277#issuecomment-292708809 and https://developer.mozilla.org/en-US/docs/Web/API/Window/self). So to have that work with jsdom-worker I also had to change the following function in the `Worker` class:

```javascript
inside.on('message', e => {
  let f = getScopeVar('self.onmessage') || getScopeVar('onmessage');
  if (f) {
    f.call(scope, e);
  }
});
```

I created a fork here: https://github.com/Charterhouse/jsdom-worker/tree/react-fix and if you want to try it out quickly I also published an npm package under [@react-frontend-developer/jsdom-worker](https://www.npmjs.com/package/@react-frontend-developer/jsdom-worker).

Sorry for rushing out things a bit, but I needed this to work in a project immediately.

**Comment by developit** [comment]
no problem - fwiw `npm link` or git installation is a little easier for that than deploying copies to npm ;)

I'm surprised the workaround was needed for `self.onmessage`, but that seems like a good fix.

Perhaps the solution for fetch/URL reset is to incorporate your property detection strategy into the Worker constructor?  Each time you invoke the constructor it'd check for fetch having been replaced and then re-inject it if it was.

**Comment by marcinczenko** [comment]
> no problem - fwiw npm link or git installation is a little easier for that than deploying copies to npm ;)

yeah - I needed in too many places.

For other things I got a bit out of loop. But I will get back to it soon.

**Comment by agilgur5** [comment]
I was getting a `TypeError: e.match is not a function` from `global.fetch` (pointing to one of the `url.match` function calls) and switching to (@react-frontend-developer/jsdom-worker)[https://www.npmjs.com/package/@react-frontend-developer/jsdom-worker] resolved the issue.

I'm not entirely sure how it's related and haven't dug into this code to know what the problem/resolution is, but thought I might add that since there seems to be some relation

**Comment by ywen** [comment]
> I was getting a `TypeError: e.match is not a function` from `global.fetch` (pointing to one of the `url.match` function calls) and switching to [@react-frontend-developer/jsdom-worker](https://www.npmjs.com/package/@react-frontend-developer/jsdom-worker) resolved the issue.
> 
> I'm not entirely sure how it's related and haven't dug into this code to know what the problem/resolution is, but thought I might add that since there seems to be some relation

How did you install/use `@react-frontend-developer/jsdom-worker` ?

**Comment by agilgur5** [comment]
> How did you install/use @react-frontend-developer/jsdom-worker ?

Pretty ordinarily: `npm i -D @react-frontend-developer/jsdom-worker` and `import '@react-frontend-developer/jsdom-worker'`
