### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by SecurityInsanity** [developit/jsdom-worker#7]
:wave: Thanks for the great library!

It looks like support for importScripts was added in: https://github.com/developit/jsdom-worker/pull/2 However it looks like a release hasn't happened since then. Would is be possible to get a new release so I can use this?

**Comment by reyronald** [comment]
I also need the latest version deployed please 🙈 

Great package by the way ! Extremely convenient, thanks a lot for putting this out there 🙏

**Comment by developit** [comment]
[0.2.0](https://github.com/developit/jsdom-worker/releases/tag/0.2.0) is out!
